package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// NamespaceQueueSpec defines the desired state of NamespaceQueue
type NamespaceQueueSpec struct {
	Capability  corev1.ResourceList `json:"capability"`
	Guarantee   corev1.ResourceList `json:"guarantee"`
	Reclaimable *bool               `json:"reclaimable,omitempty"`
	ParentQueue string              `json:"parentQueue"`
	Weight      int32               `json:"weight"`
}

// NamespaceQueueStatus defines the observed state of NamespaceQueue
type NamespaceQueueStatus struct {
	State      string              `json:"state"`
	Allocated  corev1.ResourceList `json:"allocated"`
	Conditions []metav1.Condition  `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type NamespaceQueue struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   NamespaceQueueSpec   `json:"spec,omitempty"`
	Status NamespaceQueueStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true
type NamespaceQueueList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NamespaceQueue `json:"items"`
}

// DeepCopyObject methods for runtime.Object interface


// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceQueue.
func (in *NamespaceQueue) DeepCopy() *NamespaceQueue {
       if in == nil {
	       return nil
       }
       out := new(NamespaceQueue)
       *out = *in
       out.ObjectMeta = *in.ObjectMeta.DeepCopy()
       out.Spec = in.Spec
       out.Status = in.Status
       return out
}

func (in *NamespaceQueue) DeepCopyObject() runtime.Object {
       if in == nil {
	       return nil
       }
       return in.DeepCopy()
}



// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceQueueList.
func (in *NamespaceQueueList) DeepCopy() *NamespaceQueueList {
       if in == nil {
	       return nil
       }
       out := new(NamespaceQueueList)
       *out = *in
       out.ListMeta = *in.ListMeta.DeepCopy()
       if in.Items != nil {
	       out.Items = make([]NamespaceQueue, len(in.Items))
	       for i := range in.Items {
		       out.Items[i] = *in.Items[i].DeepCopy()
	       }
       }
       return out
}

func (in *NamespaceQueueList) DeepCopyObject() runtime.Object {
       if in == nil {
	       return nil
       }
       return in.DeepCopy()
}
